defmodule VesperWeb.Endpoint do
  use Phoenix.Endpoint, otp_app: :vesper

  # The session will be stored in the cookie and signed,
  # this means its contents can be read but not tampered with.
  # Set :encryption_salt if you would also like to encrypt it.
  @session_options [
    store: :cookie,
    key: "_vesper_key",
    signing_salt: "t9cq9Hjy",
    same_site: "Lax"
  ]

  socket "/socket", VesperWeb.UserSocket,
    websocket: [
      timeout: 45_000,
      compress: true,
      max_frame_size: 1_048_576
    ],
    longpoll: false

  socket "/live", Phoenix.LiveView.Socket,
    websocket: [connect_info: [session: @session_options]],
    longpoll: [connect_info: [session: @session_options]]

  # Serve at "/" the static files from "priv/static" directory.
  #
  # When code reloading is disabled (e.g., in production),
  # the `gzip` option is enabled to serve compressed
  # static files generated by running `phx.digest`.
  plug Plug.Static,
    at: "/",
    from: :vesper,
    gzip: not code_reloading?,
    only: VesperWeb.static_paths(),
    raise_on_missing_only: code_reloading?

  # Code reloading can be explicitly enabled under the
  # :code_reloader configuration of your endpoint.
  if code_reloading? do
    plug Phoenix.CodeReloader
    plug Phoenix.Ecto.CheckRepoStatus, otp_app: :vesper
  end

  plug Phoenix.LiveDashboard.RequestLogger,
    param_key: "request_logger",
    cookie_key: "request_logger"

  plug Plug.RequestId
  plug Plug.Telemetry, event_prefix: [:phoenix, :endpoint]

  plug Plug.Parsers,
    parsers: [:urlencoded, :multipart, :json],
    pass: ["*/*"],
    json_decoder: Phoenix.json_library(),
    # Max request body size — must match FileStorage.max_upload_size/0.
    # See "File upload limits" in the project README for details.
    length: 52_428_800

  plug Plug.MethodOverride
  plug Plug.Head
  plug Plug.Session, @session_options
  # Resolve origins at request time. Runtime configuration is loaded after this
  # module is compiled, so a bare `plug CORSPlug` would freeze the wildcard
  # default into production releases.
  plug CORSPlug,
    origin: &VesperWeb.OriginPolicy.cors_origins/0,
    methods: ["GET", "POST", "PUT", "PATCH", "DELETE", "OPTIONS"],
    headers: ["authorization", "content-type"]

  plug VesperWeb.Router
end
